### ISSUE TITLE
Finishing up

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/TableSchema.jl#2]
# Description

This issue describes the set of tasks to complete in order to finish up work on the library.

# Tasks

- [x] Touch base with the @jobarratt and @pwalsh to notify that you consider the work complete
- [x] Provide a short description / link to code for how each action is implemented, with a link to unit tests that prove each action
- [x] Tag your candidate code as v0.1
- [x] Setup travis to auto deploy tagged versions to the package management solution for your language
- [x] Ensure that the OKI account on the package management platform is an administrator/maintainer of the package, along with yourself
- [x] Receive code review from @pwalsh and address any remaining issues
- [x] Publish final version

# Links

- [Actions with links to tests](https://github.com/frictionlessdata/TableSchema.jl/blob/master/DESIGN.md#functional-specification)
- v0.1 PR: https://github.com/frictionlessdata/TableSchema.jl/pull/26
- [Travis CI](https://travis-ci.org/frictionlessdata/tableschema-jl)

**Comment by loleg** [comment]
Updated status, adding links.

**Comment by loleg** [comment]
Assigning to @pwalsh for code review.

**Comment by jobarratt** [comment]
@loleg thank you. I've moved the code review to Serah, who may ask for @roll to take a look too.

**Comment by loleg** [comment]
![screenshot from 2019-01-28 12-36-58](https://user-images.githubusercontent.com/31819/51834341-4b2e3a80-22fa-11e9-8259-6f7f6f7c818b.png)

TableSchema installs just fine in the current Julia release. This should help our release of DataPackage.jl and subsequent activities.
